### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [albfan/git-changemail#10]
Hello!

I found this script from https://stackoverflow.com/a/27754778/5287257

Could you please add information about a license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by albfan** [comment]
Thanks to bring this to my attention.

Let me know if #11 fixes it or any further change is needed

**Comment by vazhnov** [comment]
@albfan , #11 looks great!
