### ISSUE TITLE
integer expression expected

### ISSUE THREAD

**Issue by valtoni** [albfan/git-changemail#3]
Lines 11 and 15 cause "integer expression expected".

**Comment by albfan** [comment]
That is code tot allow easy debugging

it is used as

```
$ export git_changemail_DEBUG=10
$ git changemail -a old@email.com -n newname -m new@email.com
(script executed with set -xv)
```

but variable name depends on finalname of your script

test `echo $SCRIPT_DEBUG` to get finalname and do

```
$ export git_changemail_DEBUG= 
```

or whatever your varname is, that should be enough

Anyway I must check value returned to avoid that error. I use it in a lot of projects!

If it bothers you, you can remove all SCRIPT_DEBUG related code, as I say it is only for debug purposes.

**Comment by valtoni** [comment]
Ok, sure. But, i'm final user of script and if the variable "git_changemail_DEBUG" is clear (my case) these warning messages occur. I'm using cygwin and line 11 can be replaced to:

``` bash
case "$(uname -s)" in
   CYGWIN*|MINGW32*|MSYS*)
     eval SCRIPT_DEBUG="\$$(cygpath $(basename $0)| tr - _)_DEBUG"
     ;;
   *)
     eval SCRIPT_DEBUG="\$$(basename $0 | tr - _)_DEBUG"
     ;;
esac
```

But, after all, the script compare a string with an integer. Can you test if SCRIPT_DEBUG is an integer before test? :)

**Comment by albfan** [comment]
`cygpath` is an horrendous trick to stay forever in the window-linux mix. I recommend you to link git-changemail somewhere in your `PATH` and ease your workflows by the smart link existing on git between

```
git-whatever 
```

and 

```
git whatever 
```

Notice space. See [this](http://stackoverflow.com/a/6719718)

That way you can issue `git changemail` from any repo as an ordinal git command.

**Comment by valtoni** [comment]
Thanks!
