### ISSUE TITLE
You can not specify a name with spaces on the -n parameter, take 2

### ISSUE THREAD

**Issue by pmorch** [albfan/git-changemail#7]
This is issue #1, take 2:

```
> git changemail -b peter@morch.com -m peter@morch.com -n 'Peter Valdemar Mørch' .
fatal: ambiguous argument 'Valdemar': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

The problem is in these lines in the script:

```
if [ "'$OLD_AUTHOR_EMAIL'" != "" ] && [ "$GIT_AUTHOR_EMAIL" = "'$OLD_AUTHOR_EMAIL'" ]
then
    an="'$NEW_AUTHOR_NAME'"
    am="'$NEW_AUTHOR_EMAIL'"
fi
```

Since `$NEW_AUTHOR_NAME` does contain spaces, the `'$VAR'` trick to put the contents of `$VAR` into the script argument to `git filter-branch` isn't going to work. Sorry, I don't have a better idea, but this is buggy. #1 only changed the parameters to `show_change`, but didn't actually fix the problem as far as I can see.

**Comment by albfan** [comment]
If you are interested in script quotes hell I can explain you:

http://stackoverflow.com/questions/7267614/bash-exec-and-the-quoting-hell
http://mywiki.wooledge.org/BashFAQ/050

hope you are not!

Anyway your example shows me a boilerplate definition of email (when clearly you don't want to change the email) I have fixed it on #8 

thanks for the feedback!
